# Generated by Django 2.2.11 on 2020-04-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ce',
            name='sso_or_sfsp',
            field=models.CharField(choices=[('SSO', 'Seamless Summer Option'), ('SFSP', 'Summer Food Service Program')], max_length=255),
        ),
    ]
