# Generated by Django 2.2.9 on 2020-01-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ce',
            name='sso_or_sfsp',
            field=models.CharField(choices=[('SSO', 'Seamless Summer Option'), ('SFSP', 'Summer Food Service Program'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
