# Generated by Django 2.2 on 2019-04-26 03:24

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190425_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='program_contact_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
