# Generated by Django 2.2.9 on 2020-01-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ce_sso_or_sfsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='valid_coordinates',
            field=models.BooleanField(default=True),
        ),
    ]
