# Generated by Django 2.2.1 on 2019-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190509_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ce',
            name='program_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='program_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
