# Generated by Django 2.2.1 on 2019-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190509_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_salutation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_title_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='county',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='county_district_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='mailing_address1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='mailing_address2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='mailing_city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='mailing_state',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='mailing_zip',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='program_year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='street_address1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='street_address2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='street_city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='street_state',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='street_zip',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_salutation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_title_position',
            field=models.CharField(blank=True, max_length=150000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='county',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='days_of_operation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailing_zip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='meal_types_served',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_salutation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_title_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_salutation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_title_position',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sfsp_site_type',
            field=models.CharField(blank=True, choices=[('CAMP_NON_RES', 'Camp-Non-Residential'), ('CAMP_RES', 'Camp-Residential'), ('CLOSED_ENROLLED_NEEDY', 'Closed-Enrolled in Needy Area'), ('CLOSED_ENROLLED_NON_NEEDY', 'Closed-Enrolled in Non-Needy Area'), ('HOMELESS', 'Homeless'), ('OPEN', 'Open'), ('ROPEN', 'Restricted Open'), ('OTHER', 'Other')], default='OTHER', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_salutation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_title_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='street_city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='street_state',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='street_zip',
            field=models.CharField(max_length=500),
        ),
    ]
