# Generated by Django 2.2.5 on 2019-11-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190509_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ce',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ce',
            name='mailing_address1',
        ),
        migrations.RemoveField(
            model_name='ce',
            name='mailing_address2',
        ),
        migrations.RemoveField(
            model_name='ce',
            name='mailing_city',
        ),
        migrations.RemoveField(
            model_name='ce',
            name='mailing_state',
        ),
        migrations.RemoveField(
            model_name='ce',
            name='mailing_zip',
        ),
        migrations.RemoveField(
            model_name='site',
            name='mailing_address1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='mailing_address2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='mailing_city',
        ),
        migrations.RemoveField(
            model_name='site',
            name='mailing_state',
        ),
        migrations.RemoveField(
            model_name='site',
            name='mailing_zip',
        ),
        migrations.AlterField(
            model_name='ce',
            name='ce_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
