# Generated by Django 2.2.5 on 2019-11-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20191118_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_date',
            field=models.DateField(),
        ),
    ]
