# Generated by Django 2.2.5 on 2019-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20191118_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
