version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"

  web:
    depends_on:
      - db
    build: ./web
    volumes:
      - ./web:/code
      - ./static:/static
    expose:
      - "8000"

  cronjobs:
    build: ./cronjobs
    volumes:
      - ./web:/code

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
