version: '3'

services:
  db:
    image: postgres

  web:
    depends_on:
      - db
    build: ./web
    ports:
      - 8000:8000
    volumes:
      - ./web:/code

  cronjobs:
    build: ./cronjobs

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
