# Generated by Django 2.2 on 2019-04-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=20)),
                ('type_of_agency', models.CharField(choices=[('EDUCATIONAL', 'Educational Institution'), ('GOV_AGENCY', 'Government Agency'), ('INDIAN_TRIBE', 'Indian Tribe'), ('MILITARY', 'Military Installation'), ('PRIVATE_NON_PROFIT', 'Private Non-Profit Organization'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('county_district_code', models.CharField(max_length=7)),
                ('esc', models.IntegerField()),
                ('tda_region', models.IntegerField()),
                ('street_address1', models.CharField(max_length=100)),
                ('street_address2', models.CharField(max_length=100, null=True)),
                ('street_city', models.CharField(max_length=50)),
                ('street_state', models.CharField(max_length=20)),
                ('street_zip', models.IntegerField()),
                ('mailing_address1', models.CharField(max_length=100)),
                ('mailing_address2', models.CharField(max_length=100, null=True)),
                ('mailing_city', models.CharField(max_length=50)),
                ('mailing_state', models.CharField(max_length=20)),
                ('mailing_zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_current_record', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('sso_or_sfsp', models.CharField(choices=[('SSO', 'Seamless Summer Option'), ('SFSP', 'Summer Food Service Program'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('site_id', models.IntegerField()),
                ('type_of_snp_org', models.CharField(choices=[('CHARTER', 'Charter'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('RCCI', 'Residential Child Care Institution'), ('OTHER', 'Other')], default='OTHER', max_length=100, null=True)),
                ('type_of_sfsp_org', models.CharField(choices=[('NSC', 'Nonresidential Summer Camp'), ('PNP', 'Private Non Profit'), ('RC', 'Residential Camp'), ('SFA', 'School Food Authority'), ('UG', 'Unit of Government'), ('OTHER', 'Other')], default='OTHER', max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('rural_or_urban_code', models.CharField(choices=[('RURAL', 'Rural'), ('URBAN', 'Urban')], max_length=20, null=True)),
                ('sso_site_type', models.CharField(choices=[('CAMP', 'Camp'), ('CLOSED', 'Closed'), ('OPEN', 'Open'), ('ROPEN', 'Open Restricted'), ('OTHER', 'Other')], default='OTHER', max_length=20, null=True)),
                ('sfsp_site_type', models.CharField(choices=[('CAMP_NON_RES', 'Camp-Non-Residential'), ('CAMP_RES', 'Camp-Residential'), ('CLOSED_ENROLLED_NEEDY', 'Closed-Enrolled in Needy Area'), ('CLOSED_ENROLLED_NON_NEEDY', 'Closed-Enrolled in Non-Needy Area'), ('HOMELESS', 'Homeless'), ('OPEN', 'Open'), ('ROPEN', 'Restricted Open'), ('OTHER', 'Other')], default='OTHER', max_length=50, null=True)),
                ('street_address1', models.CharField(max_length=100)),
                ('street_address2', models.CharField(max_length=100, null=True)),
                ('street_city', models.CharField(max_length=50)),
                ('street_state', models.CharField(max_length=20)),
                ('street_zip', models.IntegerField()),
                ('mailing_address1', models.CharField(max_length=100, null=True)),
                ('mailing_address2', models.CharField(max_length=100, null=True)),
                ('mailing_city', models.CharField(max_length=50, null=True)),
                ('mailing_state', models.CharField(max_length=20, null=True)),
                ('mailing_zip', models.IntegerField(null=True)),
                ('program_contact_salutation', models.CharField(max_length=20, null=True)),
                ('program_contact_first_name', models.CharField(max_length=30)),
                ('program_contact_last_name', models.CharField(max_length=30)),
                ('program_contact_title_position', models.CharField(max_length=30)),
                ('program_contact_email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('days_of_operation', models.CharField(max_length=16)),
                ('meal_types_served', models.CharField(max_length=50)),
                ('ce_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.CE')),
            ],
        ),
    ]
