# Generated by Django 2.2.1 on 2019-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190508_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ce',
            name='mailing_zip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ce',
            name='street_zip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailing_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='street_zip',
            field=models.CharField(max_length=20),
        ),
    ]
