# Generated by Django 2.2.1 on 2019-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190509_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_title_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_title_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_title_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_title_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_title_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
