# Generated by Django 2.2.1 on 2019-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190509_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='childnutdir_salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='county',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ce',
            name='county_district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ce',
            name='superintendent_salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='days_of_operation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailing_address1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailing_address2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_auth_rep_salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='program_contact_salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_supervisor_salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='street_address1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='street_address2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
