# Generated by Django 2.2.1 on 2019-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190509_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ce',
            name='type_of_agency',
            field=models.CharField(choices=[('EDUCATIONAL', 'Educational Institution'), ('GOV_AGENCY', 'Government Agency'), ('INDIAN_TRIBE', 'Indian Tribe'), ('MILITARY', 'Military Installation'), ('PRIVATE_NON_PROFIT', 'Private Non-Profit Organization'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
